# =============================================================================
# parser.py — SababaLang Parser
# =============================================================================
# The parser is Stage 2 of the compiler pipeline.
# It reads the flat list of Tokens generated by the Lexer and constructs
# an Abstract Syntax Tree (AST). It enforces the grammatical rules of the
# language and throws fun Hebrew errors when syntax is violated.
# =============================================================================

from sababa_token import TokenType, Token
from ast_nodes import *
from lexer import SababaError

class Parser:
    def __init__(self, tokens: list[Token], verbose: bool = False):
        self.tokens = tokens
        self.pos = 0
        self.verbose = verbose

    # ================================================================
    # Public API
    # ================================================================

    def parse(self) -> Program:
        statements = []
        self._consume(TokenType.YALLA, "אחי, הקוד חייב להתחיל ב-'יאללה'")
        
        while not self._check(TokenType.SIYAMNU) and not self._is_at_end():
            statements.append(self._statement())
            
        self._consume(TokenType.SIYAMNU, "שכחת לכתוב 'סיימנו' בסוף הקוד!")
        
        # ─── الحل هنا: التأكد من عدم وجود أي شيء بعد סיימנו ───
        if not self._is_at_end():
            raise SababaError(
                f"מה זה הקשקוש הזה אחרי 'סיימנו'? מצאתי: '{self._peek().value}'", 
                self._peek().line
            )
            
        return Program(statements)
        
    # ================================================================
    # Statement Parsing
    # ================================================================

    def _statement(self) -> ASTNode:
        if self._match(TokenType.MISPAR, TokenType.TEKST):
            return self._var_decl()
        if self._check(TokenType.IDENTIFIER):
            return self._assignment()
        if self._match(TokenType.IM):
            return self._if_stmt()
        if self._match(TokenType.KHALOD):
            return self._while_stmt()
        if self._match(TokenType.TADPIS):
            return self._print_stmt()
        if self._match(TokenType.TACHZIR):
            return self._return_stmt()
        if self._match(TokenType.FUNCTION):
            return self._function_def()
        if self._match(TokenType.RESHIMA):
            return self._var_decl() # تعريف المصفوفة هو نفس تعريف المتغير
        if self._match(TokenType.LEKOL):
            return self._for_stmt()
        if self._match(TokenType.YAVE):
            return self._import_stmt()
            
        raise SababaError(
            f"אחי, אני לא מבין מה אתה רוצה פה: '{self._peek().value}'", 
            self._peek().line
        )
    def _for_stmt(self) -> ForStmt:
        # لتبسيط اللغة، سنستخدم صيغة: לכל מספר i שים 0 ; i < 10 ; i שים i + 1 { ... }
        # وبما أننا لم نضف ; للـ lexer بعد، سنستخدم الفاصلة , للفصل بين أجزاء الـ For
        self._consume(TokenType.MISPAR, "צפה ל'מספר' בתחילת לכל")
        init = self._var_decl()
        self._consume(TokenType.COMMA, "צפה לפסיק , אחרי ההתחלה")
        condition = self._expression()
        self._consume(TokenType.COMMA, "צפה לפסיק , אחרי התנאי")
        step = self._assignment()
        body = self._block()
        return ForStmt(init, condition, step, body)
        
    def _var_decl(self) -> VarDecl:
        var_type = self._previous().value
        name = self._consume(TokenType.IDENTIFIER, "אחי, חסר שם למשתנה").value
        self._consume(TokenType.SIM, "אחי, חסר 'שים' (השמה) אחרי השם של המשתנה")
        expr = self._expression()
        return VarDecl(var_type, name, expr)

    def _assignment(self) -> Assign:
        name = self._consume(TokenType.IDENTIFIER, "חסר שם משתנה").value
        self._consume(TokenType.SIM, "שכחת 'שים' פה אחי. איך נכניס ערך?")
        expr = self._expression()
        return Assign(name, expr)

    def _if_stmt(self) -> IfStmt:
        condition = self._expression()
        self._consume(TokenType.AZ, "אחי, חסר 'אז' אחרי התנאי של ה-'אם'")
        then_branch = self._block()
        
        else_branch = None
        if self._match(TokenType.ACHERET):
            else_branch = self._block()
            
        return IfStmt(condition, then_branch, else_branch)

    def _while_stmt(self) -> WhileStmt:
        condition = self._expression()
        body = self._block()
        return WhileStmt(condition, body)

    def _print_stmt(self) -> PrintStmt:
        expr = self._expression()
        return PrintStmt(expr)

    def _return_stmt(self) -> ReturnStmt:
        expr = self._expression()
        return ReturnStmt(expr)

    def _block(self) -> Block:
        self._consume(TokenType.LBRACE, "אחי, חסר סוגר שמאלי { כדי לפתוח בלוק")
        statements = []
        while not self._check(TokenType.RBRACE) and not self._is_at_end():
            statements.append(self._statement())
        self._consume(TokenType.RBRACE, "אחי, שכחת לסגור את הבלוק עם }")
        return Block(statements)
    def _import_stmt(self) -> ImportStmt:
        # نتوقع أن يكون اسم الملف نصاً (String)
        module_token = self._consume(TokenType.STRING, "אחי, חסר שם קובץ לייבוא בתוך גרשיים!")
        return ImportStmt(module_token.value)
    # ================================================================
    # Expression Parsing (Precedence: lowest to highest)
    # ================================================================

    def _expression(self) -> ASTNode:
        return self._logical_or()

    def _logical_or(self) -> ASTNode:
        expr = self._logical_and()
        while self._match(TokenType.O):
            op = self._previous().value
            right = self._logical_and()
            expr = BinaryOp(expr, op, right)
        return expr

    def _logical_and(self) -> ASTNode:
        expr = self._equality()
        while self._match(TokenType.VEGAM):
            op = self._previous().value
            right = self._equality()
            expr = BinaryOp(expr, op, right)
        return expr

    def _equality(self) -> ASTNode:
        expr = self._comparison()
        while self._match(TokenType.EQ_EQ, TokenType.BANG_EQ):
            op = self._previous().value
            right = self._comparison()
            expr = BinaryOp(expr, op, right)
        return expr

    def _comparison(self) -> ASTNode:
        expr = self._term()
        while self._match(TokenType.GT, TokenType.LT, TokenType.GT_EQ, TokenType.LT_EQ):
            op = self._previous().value
            right = self._term()
            expr = BinaryOp(expr, op, right)
        return expr

    def _term(self) -> ASTNode:
        expr = self._factor()
        while self._match(TokenType.PLUS, TokenType.MINUS):
            op = self._previous().value
            right = self._factor()
            expr = BinaryOp(expr, op, right)
        return expr

    def _factor(self) -> ASTNode:
        expr = self._unary()
        while self._match(TokenType.STAR, TokenType.SLASH):
            op = self._previous().value
            right = self._unary()
            expr = BinaryOp(expr, op, right)
        return expr

    def _unary(self) -> ASTNode:
        if self._match(TokenType.LO, TokenType.MINUS):
            op = self._previous().value
            right = self._unary()
            return UnaryOp(op, right)
        return self._primary()

    def _primary(self) -> ASTNode:
        if self._match(TokenType.SABABA):
            return Literal(True, "מספר")
        if self._match(TokenType.BASA):
            return Literal(False, "מספר")
        if self._match(TokenType.NUMBER):
            return Literal(int(self._previous().value), "מספר")
        if self._match(TokenType.STRING):
            return Literal(self._previous().value, "טקסט")
            
        # ── קריאת מערך חדש [1, 2, 3] ──
        if self._match(TokenType.LBRACK):
            elements = []
            if not self._check(TokenType.RBRACK):
                elements.append(self._expression())
                while self._match(TokenType.COMMA):
                    elements.append(self._expression())
            self._consume(TokenType.RBRACK, "שכחת לסגור סוגריים מרובעים ]")
            return ArrayLiteral(elements)

        # ── מזהים, קריאה לפונקציה, וגישה למערך ──
        if self._match(TokenType.IDENTIFIER):
            name = self._previous().value
            
            # האם זו קריאה לפונקציה? func(x, y)
            if self._match(TokenType.LPAREN):
                args = []
                if not self._check(TokenType.RPAREN):
                    args.append(self._expression())
                    while self._match(TokenType.COMMA):
                        args.append(self._expression())
                self._consume(TokenType.RPAREN, "שכחת ) בקריאה לפונקציה")
                return FunctionCall(name, args)
                
            # האם זו גישה למערך? arr[0]
            if self._match(TokenType.LBRACK):
                index = self._expression()
                self._consume(TokenType.RBRACK, "שכחת ] אחרי האינדקס")
                return ArrayAccess(name, index)
                
            return VarAccess(name)

        if self._match(TokenType.LPAREN):
            expr = self._expression()
            self._consume(TokenType.RPAREN, "אחי, פתחת סוגריים ( אבל שכחת לסגור )")
            return expr

        raise SababaError(
            f"מה נסגר פה? לא ציפיתי ל-'{self._peek().value}' באמצע ביטוי", 
            self._peek().line
        )

    # ================================================================
    # Parsing Helpers
    # ================================================================
    def _function_def(self) -> FunctionDef:
        name = self._consume(TokenType.IDENTIFIER, "אחי, חסר שם לפונקציה").value
        self._consume(TokenType.LPAREN, "שכחת סוגריים ( אחרי שם הפונקציה")
        
        params = []
        if not self._check(TokenType.RPAREN):
            params.append(self._consume(TokenType.IDENTIFIER, "צפה לשם משתנה").value)
            # التعديل هنا: جعلناه يقرأ الفاصلة بشكل صحيح
            while self._match(TokenType.COMMA): 
                params.append(self._consume(TokenType.IDENTIFIER, "צפה לשם משתנה אחרי הפסיק").value)
                
        self._consume(TokenType.RPAREN, "שכחת לסגור סוגריים )")
        body = self._block()
        return FunctionDef(name, params, body)
        
    def _match(self, *types) -> bool:
        """Check if current token matches any of the types, and advance if it does."""
        for t in types:
            if self._check(t):
                self._advance()
                return True
        return False

    def _consume(self, type_: TokenType, error_message: str) -> Token:
        """Expect a specific token type next, otherwise throw a custom Sababa error."""
        if self._check(type_):
            return self._advance()
        raise SababaError(error_message, self._peek().line)

    def _check(self, type_: TokenType) -> bool:
        """Return True if the current token is of the given type, without advancing."""
        if self._is_at_end():
            return False
        return self._peek().type == type_

    def _advance(self) -> Token:
        """Move cursor forward and return the previous token."""
        if not self._is_at_end():
            self.pos += 1
        return self._previous()

    def _is_at_end(self) -> bool:
        return self._peek().type == TokenType.EOF

    def _peek(self) -> Token:
        return self.tokens[self.pos]

    def _previous(self) -> Token:
        return self.tokens[self.pos - 1]